trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Setup Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    # Configure Databricks CLI
    echo "Configuring Databricks CLI"
    databricks configure --token <<EOF
    $(DATABRICKS_HOST)
    $(DATABRICKS_TOKEN)
    EOF
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
  displayName: 'Configure Databricks CLI'

- script: |
    databricks jobs run-now --job-id <209754261247957> --notebook-params '{"input_path": "dbfs:/FileStore/tables/hr_employee_churn_data.csv", "output_path": "/processed_hr_employee_churn_data.csv"}'
    databricks jobs run-now --job-id <538543884377785> --notebook-params '{"input_path": "/processed_hr_employee_churn_data.csv"}'
  displayName: 'Run Databricks scripts'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'
